services:
  - type: web
    name: fahrtenbuch
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: <deine-postgresql-url>
